# Generated by Django 4.2.23 on 2025-06-29 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_alter_loan_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZakatYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hijri_year', models.PositiveIntegerField(help_text='The Hijri year for Zakat calculation (e.g., 1446)', unique=True)),
            ],
            options={
                'ordering': ['-hijri_year'],
            },
        ),
    ]
