# Generated by Django 4.2.23 on 2025-06-29 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_zakatyear'),
    ]

    operations = [
        migrations.AddField(
            model_name='zakatyear',
            name='nisab_amount',
            field=models.DecimalField(decimal_places=2, default=5900.0, help_text='The Nisab amount for this year in your currency (e.g., 5000.00)', max_digits=10),
        ),
    ]
