# Generated by Django 4.2.23 on 2025-06-29 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_zakatyear_nisab_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zakatyear',
            name='hijri_year',
            field=models.PositiveIntegerField(default=1446, help_text='The Hijri year for Zakat calculation (e.g., 1446)', unique=True),
        ),
    ]
